"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Query = exports.Post = exports.Param = exports.Module = exports.Injectable = exports.Get = exports.Factory = exports.Controller = exports.Body = void 0;
require("reflect-metadata");
var Controller_1 = require("./Controller");
exports.Controller = Controller_1.default;
var Factory_1 = require("./Factory");
exports.Factory = Factory_1.default;
var Http_1 = require("./Http");
Object.defineProperty(exports, "Get", { enumerable: true, get: function () { return Http_1.Get; } });
Object.defineProperty(exports, "Post", { enumerable: true, get: function () { return Http_1.Post; } });
var Injectable_1 = require("./Injectable");
exports.Injectable = Injectable_1.default;
var Module_1 = require("./Module");
exports.Module = Module_1.default;
var RouterParams_1 = require("./RouterParams");
Object.defineProperty(exports, "Body", { enumerable: true, get: function () { return RouterParams_1.Body; } });
Object.defineProperty(exports, "Param", { enumerable: true, get: function () { return RouterParams_1.Param; } });
Object.defineProperty(exports, "Query", { enumerable: true, get: function () { return RouterParams_1.Query; } });
