export const INJECTABLE_WATERMARK = Symbol('INJECTABLE_WATERMARK')
export const BASE_PATH = Symbol('BASE_PATH')
export const PATH = Symbol('PATH')
export const METHOD = Symbol('METHOD')
export const PARAMS = Symbol('PARAMS')
